[functions.sync-discord-guilds]
verify_jwt = false

[functions.billing-webhook]
verify_jwt = false

[functions.billing-create-checkout]
verify_jwt = false

[functions.create-customer-portal-session]
verify_jwt = false