MAIN=package.json
MEMORY=512
VERSION=recommended
DISPLAY_NAME=TON618 Web Dashboard
DESCRIPTION=Landing page, dashboard, and billing portal for TON618 Discord bot
SUBDOMAIN=ton618-web
START=npm run start:squarecloud
AUTORESTART=true
PORT=80
HEALTHCHECK_PATH=/